# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0esawtooth_ddpoa\"F\n\tBootstrap\x12\x15\n\rchain_head_id\x18\x01 \x01(\x0c\x12\x12\n\nnum_blocks\x18\x02 \x01(\r\x12\x0e\n\x06pre_id\x18\x03 \x01(\x0c\"\xbc\x01\n\x10\x43onsensusMessage\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.sawtooth_ddpoa.MessageType\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\r\n\x05votes\x18\x03 \x03(\t\x12\x0e\n\x06result\x18\x04 \x03(\t\x12\r\n\x05\x65poch\x18\x05 \x01(\r\x12,\n\tbootstrap\x18\x06 \x01(\x0b\x32\x19.sawtooth_ddpoa.Bootstrap\x12\x0e\n\x06signer\x18\x07 \x01(\t\"\x12\n\x05\x45mpty\x12\t\n\x01_\x18\x01 \x01(\x08*p\n\x0bMessageType\x12\x08\n\x04VOTE\x10\x00\x12\x0f\n\x0bVOTE_RESULT\x10\x01\x12\x0e\n\nEMPTY_SLOT\x10\x02\x12\r\n\tBOOTSTRAP\x10\x03\x12\x15\n\x11\x42OOTSTRAP_REQUEST\x10\x04\x12\x10\n\x0cSYNC_REQUEST\x10\x05\x32\x97\x01\n\x0c\x43onsensusRPC\x12\x41\n\x04Ping\x12\x15.sawtooth_ddpoa.Empty\x1a .sawtooth_ddpoa.ConsensusMessage\"\x00\x12\x44\n\x07Message\x12 .sawtooth_ddpoa.ConsensusMessage\x1a\x15.sawtooth_ddpoa.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=316
  _MESSAGETYPE._serialized_end=428
  _BOOTSTRAP._serialized_start=33
  _BOOTSTRAP._serialized_end=103
  _CONSENSUSMESSAGE._serialized_start=106
  _CONSENSUSMESSAGE._serialized_end=294
  _EMPTY._serialized_start=296
  _EMPTY._serialized_end=314
  _CONSENSUSRPC._serialized_start=431
  _CONSENSUSRPC._serialized_end=582
# @@protoc_insertion_point(module_scope)
