version: "3.6"

volumes:
  keys:

services:

  test-liveness:
    image: sawtooth-test-framework-services:latest
    build:
      context: .
      dockerfile: testing/Dockerfile
    volumes:
      - ..:/project/sawtooth-test:ro
    command: nose2-3
        -vv
        test_liveness

  smallbank-workload:
    image: hyperledger/sawtooth-smallbank-workload
    expose:
      - 8008
    command: "bash -c \"\
            sleep 10; sawtooth keygen smallbank-key; \
            smallbank-workload load --key /root/.sawtooth/keys/smallbank-key.priv --rate 10 --target http://rest-api-0:8008,http://rest-api-1:8008,http://rest-api-2:8008,http://rest-api-3:8008 \
            \""

  validator-0:
    hostname: validator-0
    image: hyperledger/sawtooth-validator:chime
    volumes:
      - keys:/shared_keys
      - ./scripts/main_validator.sh:/root/start.sh
      - ./scripts/create_network_keys.py:/root/create_network_keys.py
    expose:
      - 4004
      - 8800
      - 5005
      - 5050
    working_dir: /root
    entrypoint: ["bash", "start.sh"]
    stop_signal: SIGKILL

  validator-1:
    hostname: validator-1
    image: hyperledger/sawtooth-validator:chime
    volumes:
      - keys:/shared_keys
      - ./scripts/start.sh:/root/start.sh
      - ./scripts/create_network_keys.py:/root/create_network_keys.py
    entrypoint: ["bash", "/root/start.sh" , "1", "0", "3"]
    expose:
      - 4004
      - 8800
      - 5005
      - 5050
    stop_signal: SIGKILL

  validator-2:
    hostname: validator-2
    image: hyperledger/sawtooth-validator:chime
    volumes:
      - keys:/shared_keys
      - ./scripts/start.sh:/root/start.sh
      - ./scripts/create_network_keys.py:/root/create_network_keys.py
    entrypoint: ["bash", "/root/start.sh" , "2", "0", "3"]
    expose:
      - 4004
      - 8800
      - 5005
      - 5050
    stop_signal: SIGKILL

  validator-3:
    hostname: validator-3
    image: hyperledger/sawtooth-validator:chime
    volumes:
      - keys:/shared_keys
      - ./scripts/start.sh:/root/start.sh
      - ./scripts/create_network_keys.py:/root/create_network_keys.py
    entrypoint: ["bash", "/root/start.sh" , "3", "0", "2"]
    expose:
      - 4004
      - 8800
      - 5005
      - 5050
    stop_signal: SIGKILL

  consensus-0:
    hostname: consensus-0
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c \"python3 main.py -vv --connect tcp://validator-0:5050 \""
    stop_signal: SIGKILL
    depends_on:
      - validator-0

  consensus-1:
    hostname: consensus-1
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c \"python3 main.py -vv --connect tcp://validator-1:5050\""
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  consensus-2:
    hostname: consensus-2
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c \"\
        python3 main.py -vv --connect tcp://validator-2:5050
      \""
    stop_signal: SIGKILL
    depends_on:
      - validator-2

  consensus-3:
    hostname: consensus-3
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c \"\
        python3 main.py -vv --connect tcp://validator-3:5050
      \""
    stop_signal: SIGKILL
    depends_on:
      - validator-3

  rest-api-0:
    hostname: rest-api-0
    image: hyperledger/sawtooth-rest-api:chime
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-0:4004 --bind rest-api-0:8008
    stop_signal: SIGKILL

  rest-api-1:
    hostname: rest-api-1
    image: hyperledger/sawtooth-rest-api:chime
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL

  rest-api-2:
    hostname: rest-api-2
    image: hyperledger/sawtooth-rest-api:chime
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-2:4004 --bind rest-api-2:8008
    stop_signal: SIGKILL

  rest-api-3:
    hostname: rest-api-3
    image: hyperledger/sawtooth-rest-api:chime
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api -v --connect tcp://validator-3:4004 --bind rest-api-3:8008
    stop_signal: SIGKILL

  settings-tp-0:
    hostname: settings-tp-0
    image: hyperledger/sawtooth-settings-tp:chime
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004 -v
    stop_signal: SIGKILL

  settings-tp-1:
    hostname: settings-tp-1
    image: hyperledger/sawtooth-settings-tp:chime
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004 -v
    stop_signal: SIGKILL

  settings-tp-2:
    hostname: settings-tp-2
    image: hyperledger/sawtooth-settings-tp:chime
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004 -v
    stop_signal: SIGKILL

  settings-tp-3:
    hostname: settings-tp-3
    image: hyperledger/sawtooth-settings-tp:chime
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004 -v
    stop_signal: SIGKILL

  smallbank-tp-0:
    image: hyperledger/sawtooth-smallbank-tp-go
    expose:
      - 4004
    command: smallbank-tp-go -C tcp://validator-0:4004 --max-queue-size 1024 --worker-thread-count 32
    stop_signal: SIGKILL

  smallbank-tp-1:
    image: hyperledger/sawtooth-smallbank-tp-go
    expose:
      - 4004
    command: smallbank-tp-go -C tcp://validator-1:4004 --max-queue-size 1024 --worker-thread-count 32
    stop_signal: SIGKILL

  smallbank-tp-2:
    image: hyperledger/sawtooth-smallbank-tp-go
    expose:
      - 4004
    command: smallbank-tp-go -C tcp://validator-2:4004 --max-queue-size 1024 --worker-thread-count 32
    stop_signal: SIGKILL

  smallbank-tp-3:
    image: hyperledger/sawtooth-smallbank-tp-go
    expose:
      - 4004
    command: smallbank-tp-go -C tcp://validator-3:4004 --max-queue-size 1024 --worker-thread-count 32
    stop_signal: SIGKILL

