version: "3.6"

services:

  better-go-fast:
    image: sawtooth-ddpoa-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/project/sawtooth-ddpoa
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project/sawtooth-ddpoa/testing
    command: bash better_go_quick.sh
