---
apiVersion: v1
kind: List

items:



- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ddpoa-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: ddpoa-test
    template:
      metadata:
        labels:
          name: ddpoa-test
      spec:
        volumes:
          - name: shared
            emptyDir: {} 
        containers:
          - name: ddpoa-shell
            image: lillepus/sawtooth-admin:latest
            imagePullPolicy: IfNotPresent
            volumeMounts: 
            - name: shared 
              mountPath: /shared
            command:
              - bash
            args:
              - -c
              - |
                  rm -rf /shared/* && \
                  ls /shared && \
                  mkdir -p /shared/keys && \
                  sawtooth keygen --key-dir /shared/keys workload && \
                  while true; do sleep 30; done; \
          - name: ddpoa-workload
            image: hyperledger/sawtooth-intkey-workload:latest
            imagePullPolicy: IfNotPresent
            volumeMounts: 
            - name: shared 
              mountPath: /shared
            command:
              - bash
            args:
              - -c
              - |
                  intkey-workload \
                  --key-file /shared/keys/workload.priv \
                  --rate 4 \
                  --urls http://$SAWTOOTH_0_SERVICE_HOST:8008,http://$SAWTOOTH_1_SERVICE_HOST:8008,http://$SAWTOOTH_2_SERVICE_HOST:8008,http://$SAWTOOTH_3_SERVICE_HOST:8008,http://$SAWTOOTH_4_SERVICE_HOST:8008,http://$SAWTOOTH_5_SERVICE_HOST:8008,http://$SAWTOOTH_6_SERVICE_HOST:8008,http://$SAWTOOTH_7_SERVICE_HOST:8008,                  \
