apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    database: metrics
    user: admin
    url: http://localhost:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: admin